theme: jekyll-theme-dinky
title: Welcome to my homepage! 
description: This site will be the best way to view my resume and view my portfolio of both GIS-related and audiobook projects. Feel free to contact me if you would like to commission an assignment.
